### ISSUE TITLE
Latest download only 2GB(6GB)

### ISSUE THREAD

**Issue by slvlirnoff** [openaddresses/openaddresses#4619]
Dear all,

The latest download available on https://results.openaddresses.io/ seems to be way smaller than expected. It seems to include sources that are only of type `esri`.

Best,
Cyprien

**Comment by missinglink** [comment]
The latest copy appears to be `11GB`, wasn't it `~6GB` before this issue?

**Comment by iandees** [comment]
I fixed a few large sources and the weekly run should have finished for the first time in a couple weeks. That might have bumped it up.

**Comment by ingalls** [comment]
@iandees this ok to close?

**Comment by iandees** [comment]
Yea, I think so.

**Comment by orangejulius** [comment]
Looks like this is still an issue. The global collection on https://results.openaddresses.io is currently 9GB, whereas we have an archive from mid September that is 11GB. Pelias builds from the global collection file on the OA website come up over 50M addresses short of normal, so it does look like there's some valid data still missing.

<img width="978" alt="Screen Shot 2019-10-30 at 2 25 57 PM" src="https://user-images.githubusercontent.com/111716/67887611-fd14c480-fb21-11e9-8b3d-9cfefa5f71ec.png">

**Comment by thismakessand** [comment]
It looks like maybe the sources that are currently broken are not contained in the downloads. 
Eg [this source](https://github.com/openaddresses/openaddresses/blob/master/sources/us/ky/warren.json) is currently broken (layer went missing) and the old data is not listed at https://results.openaddresses.io/?runs=all#runs and is not contained in the download bundles.
IIRC, previously the data from the last successful run was available for download.

**Comment by iandees** [comment]
This is probably because of the change I made in https://github.com/openaddresses/machine/pull/756?

**Comment by Jnb2387** [comment]
In the US West extract, there seems to be a lot of missing sources in the download. Before the URL change there was over 3 million addresses now its around 2 million. For example Jefferson County and city_of_arvada are both working links according to the sources, but are not included in the download.

**Comment by ingalls** [comment]
We've migrated to the new batch.openaddresses.io system. If you find this happes again please feel free to open another issue
